[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'cd backend && npm install --production',
  'cd frontend && npm install --production'
]

[phases.build]
cmds = [
  'cd frontend && mkdir -p public && echo "<!DOCTYPE html><html lang=\"ru\"><head><meta charset=\"utf-8\" /><link rel=\"icon\" href=\"%PUBLIC_URL%/favicon.ico\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" /><meta name=\"theme-color\" content=\"#667eea\" /><meta name=\"description\" content=\"Photo to 3D - Превращайте фотографии в 3D модели с помощью ИИ\" /><link rel=\"apple-touch-icon\" href=\"%PUBLIC_URL%/logo192.png\" /><link rel=\"manifest\" href=\"%PUBLIC_URL%/manifest.json\" /><title>Photo to 3D - Генерация 3D моделей</title></head><body><noscript>Для работы этого приложения необходимо включить JavaScript.</noscript><div id=\"root\"></div></body></html>" > public/index.html && echo "{\"short_name\":\"Photo to 3D\",\"name\":\"Photo to 3D - Генерация 3D моделей из фотографий\",\"icons\":[{\"src\":\"favicon.ico\",\"sizes\":\"64x64 32x32 24x24 16x16\",\"type\":\"image/x-icon\"},{\"src\":\"logo192.png\",\"type\":\"image/png\",\"sizes\":\"192x192\"},{\"src\":\"logo512.png\",\"type\":\"image/png\",\"sizes\":\"512x512\"}],\"start_url\":\".\",\"display\":\"standalone\",\"theme_color\":\"#667eea\",\"background_color\":\"#764ba2\"}" > public/manifest.json && echo "# https://www.robotstxt.org/robotstxt.html\nUser-agent: *\nDisallow:" > public/robots.txt && touch public/favicon.ico public/logo192.png public/logo512.png && npm run build'
]

[start]
cmd = './start.sh'
