[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'cd backend && npm install --production',
  'cd frontend && npm install --production'
]

[phases.build]
cmds = [
  'cd frontend && chmod +x build.sh && ./build.sh'
]

[start]
cmd = 'cd backend && npm start'
