[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'cd backend && npm install --production',
  'cd frontend && npm install --production'
]

[phases.build]
cmds = [
  'cd frontend && mkdir -p public',
  'cd frontend && echo "<!DOCTYPE html>" > public/index.html',
  'cd frontend && echo "<html lang=\"ru\">" >> public/index.html',
  'cd frontend && echo "  <head>" >> public/index.html',
  'cd frontend && echo "    <meta charset=\"utf-8\" />" >> public/index.html',
  'cd frontend && echo "    <link rel=\"icon\" href=\"%PUBLIC_URL%/favicon.ico\" />" >> public/index.html',
  'cd frontend && echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />" >> public/index.html',
  'cd frontend && echo "    <meta name=\"theme-color\" content=\"#667eea\" />" >> public/index.html',
  'cd frontend && echo "    <meta name=\"description\" content=\"Photo to 3D - Превращайте фотографии в 3D модели с помощью ИИ\" />" >> public/index.html',
  'cd frontend && echo "    <link rel=\"apple-touch-icon\" href=\"%PUBLIC_URL%/logo192.png\" />" >> public/index.html',
  'cd frontend && echo "    <link rel=\"manifest\" href=\"%PUBLIC_URL%/manifest.json\" />" >> public/index.html',
  'cd frontend && echo "    <title>Photo to 3D - Генерация 3D моделей</title>" >> public/index.html',
  'cd frontend && echo "  </head>" >> public/index.html',
  'cd frontend && echo "  <body>" >> public/index.html',
  'cd frontend && echo "    <noscript>Для работы этого приложения необходимо включить JavaScript.</noscript>" >> public/index.html',
  'cd frontend && echo "    <div id=\"root\"></div>" >> public/index.html',
  'cd frontend && echo "  </body>" >> public/index.html',
  'cd frontend && echo "</html>" >> public/index.html',
  'cd frontend && echo "{" > public/manifest.json',
  'cd frontend && echo "  \"short_name\": \"Photo to 3D\"," >> public/manifest.json',
  'cd frontend && echo "  \"name\": \"Photo to 3D - Генерация 3D моделей из фотографий\"," >> public/manifest.json',
  'cd frontend && echo "  \"icons\": [" >> public/manifest.json',
  'cd frontend && echo "    {" >> public/manifest.json',
  'cd frontend && echo "      \"src\": \"favicon.ico\"," >> public/manifest.json',
  'cd frontend && echo "      \"sizes\": \"64x64 32x32 24x24 16x16\"," >> public/manifest.json',
  'cd frontend && echo "      \"type\": \"image/x-icon\"" >> public/manifest.json',
  'cd frontend && echo "    }," >> public/manifest.json',
  'cd frontend && echo "    {" >> public/manifest.json',
  'cd frontend && echo "      \"src\": \"logo192.png\"," >> public/manifest.json',
  'cd frontend && echo "      \"type\": \"image/png\"," >> public/manifest.json',
  'cd frontend && echo "      \"sizes\": \"192x192\"" >> public/manifest.json',
  'cd frontend && echo "    }," >> public/manifest.json',
  'cd frontend && echo "    {" >> public/manifest.json',
  'cd frontend && echo "      \"src\": \"logo512.png\"," >> public/manifest.json',
  'cd frontend && echo "      \"type\": \"image/png\"," >> public/manifest.json',
  'cd frontend && echo "      \"sizes\": \"512x512\"" >> public/manifest.json',
  'cd frontend && echo "    }" >> public/manifest.json',
  'cd frontend && echo "  ]," >> public/manifest.json',
  'cd frontend && echo "  \"start_url\": \".\"," >> public/manifest.json',
  'cd frontend && echo "  \"display\": \"standalone\"," >> public/manifest.json',
  'cd frontend && echo "  \"theme_color\": \"#667eea\"," >> public/manifest.json',
  'cd frontend && echo "  \"background_color\": \"#764ba2\"" >> public/manifest.json',
  'cd frontend && echo "}" >> public/manifest.json',
  'cd frontend && echo "# https://www.robotstxt.org/robotstxt.html" > public/robots.txt',
  'cd frontend && echo "User-agent: *" >> public/robots.txt',
  'cd frontend && echo "Disallow:" >> public/robots.txt',
  'cd frontend && touch public/favicon.ico public/logo192.png public/logo512.png',
  'cd frontend && npm run build'
]

[start]
cmd = './start.sh'
